version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flowable-modeler
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8070:8070"
    container_name: flowable-modeler